project_id = "xinqu-app"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = true
enable_manual_linking = false
minimum_password_length = 6

[auth.mfa]
max_enrolled_factors = 10
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.sessions]
timebox = "0s"
inactivity_timeout = "0s"

[auth.email]
enable_signup = false
double_confirm_changes = false
enable_confirmations = false
secure_password_change = false
max_frequency = "1m"
otp_length = 6
otp_expiry = 86400

[auth.sms]
enable_signup = true
enable_confirmations = false
template = "Your code is {{ .Code }}"
max_frequency = "5s"

[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
auth_token = ""

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""
skip_nonce_check = false

[analytics]
enabled = false
port = 54327
backend = "postgres"