name: xinqu_app
description: 星趣App - 故事分享平台

# 应用版本信息
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI相关依赖
  cupertino_icons: ^1.0.6  # iOS风格图标
  font_awesome_flutter: ^10.6.0  # FontAwesome图标库
  
  # 网络请求
  http: ^1.4.0
  dio: ^5.3.2
  
  # 数据库和后端服务
  supabase_flutter: ^2.3.4
  
  # 状态管理
  provider: ^6.1.1
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # 图片相关
  cached_network_image: ^3.3.0
  
  # 动画
  lottie: ^3.3.1
  
  # 工具类
  intl: ^0.20.2  # 国际化支持
  flutter_launcher_icons: ^0.14.4
  # fluwx: ^5.7.0  # 微信SDK - 暂时注释掉
  flutter_dotenv: ^5.2.1
  crypto: ^3.0.3  # 加密工具库（用于SMS签名）
  
  # JSON序列化
  json_annotation: ^4.9.0
  
  # 设备信息和分析
  device_info_plus: ^10.1.0  # 获取设备信息

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # 代码生成
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

# Flutter相关配置
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/image.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png" 